version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - antfu
  - codemirror
  - collab
  - Errorable
  - lezer
  - ofetch
  - unocss
  - vueuse
ignoreWords: []
import: []
